/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modelView.*;
import modelView.Operaciones;

/**
 *
 * @author locon
 */
public class FormularioCal extends javax.swing.JFrame {

    /**
     * Creates new form ventana3
     */
    public FormularioCal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoNum1 = new javax.swing.JTextField();
        botonSuma = new javax.swing.JButton();
        Resultado = new javax.swing.JLabel();
        campoNum2 = new javax.swing.JTextField();
        Historial = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        resta = new javax.swing.JButton();
        multi = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        seno = new javax.swing.JButton();
        coseno = new javax.swing.JButton();
        arcsen = new javax.swing.JButton();
        secante = new javax.swing.JButton();
        arcos = new javax.swing.JButton();
        cosec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 343, 277));
        setMinimumSize(new java.awt.Dimension(343, 277));
        setPreferredSize(new java.awt.Dimension(350, 400));
        setSize(new java.awt.Dimension(350, 400));
        getContentPane().setLayout(null);

        campoNum1.setMaximumSize(new java.awt.Dimension(85, 20));
        campoNum1.setMinimumSize(new java.awt.Dimension(85, 20));
        campoNum1.setPreferredSize(new java.awt.Dimension(85, 20));
        campoNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNum1ActionPerformed(evt);
            }
        });
        getContentPane().add(campoNum1);
        campoNum1.setBounds(63, 31, 85, 20);
        campoNum1.getAccessibleContext().setAccessibleName("campoNombre");

        botonSuma.setText("Suma");
        botonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSumaActionPerformed(evt);
            }
        });
        getContentPane().add(botonSuma);
        botonSuma.setBounds(40, 90, 70, 23);
        botonSuma.getAccessibleContext().setAccessibleName("botonCrear");

        Resultado.setText("Resultado");
        getContentPane().add(Resultado);
        Resultado.setBounds(140, 250, 48, 14);
        Resultado.getAccessibleContext().setAccessibleName("codigo");

        campoNum2.setMaximumSize(new java.awt.Dimension(85, 20));
        campoNum2.setMinimumSize(new java.awt.Dimension(85, 20));
        campoNum2.setPreferredSize(new java.awt.Dimension(85, 20));
        campoNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNum2ActionPerformed(evt);
            }
        });
        getContentPane().add(campoNum2);
        campoNum2.setBounds(186, 31, 85, 20);
        campoNum2.getAccessibleContext().setAccessibleName("campoCodigo");

        Historial.setText("Historial");
        Historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialActionPerformed(evt);
            }
        });
        getContentPane().add(Historial);
        Historial.setBounds(10, 290, 71, 23);

        jLabel1.setText("campo1 ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(84, 11, 40, 14);

        jLabel2.setText("campo 2 ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(206, 11, 43, 14);

        resta.setText("resta");
        resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaActionPerformed(evt);
            }
        });
        getContentPane().add(resta);
        resta.setBounds(40, 120, 70, 23);

        multi.setText("multiply");
        multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiActionPerformed(evt);
            }
        });
        getContentPane().add(multi);
        multi.setBounds(120, 90, 90, 23);

        divide.setText("dividir");
        divide.setMaximumSize(new java.awt.Dimension(69, 23));
        divide.setMinimumSize(new java.awt.Dimension(69, 23));
        divide.setPreferredSize(new java.awt.Dimension(69, 23));
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });
        getContentPane().add(divide);
        divide.setBounds(120, 120, 90, 23);

        seno.setText("seno");
        seno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senoActionPerformed(evt);
            }
        });
        getContentPane().add(seno);
        seno.setBounds(220, 90, 70, 23);

        coseno.setText("coseno");
        coseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosenoActionPerformed(evt);
            }
        });
        getContentPane().add(coseno);
        coseno.setBounds(220, 120, 70, 23);

        arcsen.setText("arcseno");
        arcsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arcsenActionPerformed(evt);
            }
        });
        getContentPane().add(arcsen);
        arcsen.setBounds(40, 150, 70, 23);

        secante.setText("secante");
        secante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secanteActionPerformed(evt);
            }
        });
        getContentPane().add(secante);
        secante.setBounds(220, 150, 70, 23);

        arcos.setText("arcocoseno");
        arcos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arcosActionPerformed(evt);
            }
        });
        getContentPane().add(arcos);
        arcos.setBounds(120, 150, 90, 23);

        cosec.setText("cosecante");
        cosec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosecActionPerformed(evt);
            }
        });
        getContentPane().add(cosec);
        cosec.setBounds(120, 180, 90, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNum1ActionPerformed

    private void botonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSumaActionPerformed
        try {
    double resultadoSuma = Operaciones.sumar(Double.parseDouble(this.getCampoNum1()), 
                                            Double.parseDouble(this.getCampoNum2()));
    Resultado.setText(String.valueOf(resultadoSuma));
    Calculadora.guardar("suma");
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Error de formato en la suma: Ingresa números válidos.");
}

    }//GEN-LAST:event_botonSumaActionPerformed

    private void campoNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNum2ActionPerformed

    private void HistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialActionPerformed
        Calculadora.MostrarHistorial();
    }//GEN-LAST:event_HistorialActionPerformed

    private void multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiActionPerformed
       try {
    double resultadoMultiplicacion = Operaciones.multiplicar(Double.parseDouble(this.getCampoNum1()), 
                                                             Double.parseDouble(this.getCampoNum2()));
    Resultado.setText(String.valueOf(resultadoMultiplicacion));
    Calculadora.guardar("multiplicación");
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Error de formato en la multiplicación: Ingresa números válidos.");
}
    }//GEN-LAST:event_multiActionPerformed

    private void senoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senoActionPerformed
        try {
    double anguloSeno = Double.parseDouble(this.getCampoNum1());
    Resultado.setText(String.valueOf(Operaciones.seno(anguloSeno)));
    Calculadora.guardar("seno");
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Error de formato en el seno: Ingresa un número válido.");
}

    }//GEN-LAST:event_senoActionPerformed

    private void arcsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arcsenActionPerformed
        try {
    double numParaArcseno = Double.parseDouble(this.getCampoNum1());
    Resultado.setText(String.valueOf(Operaciones.arcseno(numParaArcseno)));
    Calculadora.guardar("arcseno");
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Error de formato en el arcseno: Ingresa un número válido.");
}
    }//GEN-LAST:event_arcsenActionPerformed

    private void restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaActionPerformed
        try {
    double resultadoResta = Operaciones.restar(Double.parseDouble(this.getCampoNum1()), 
                                              Double.parseDouble(this.getCampoNum2()));
    Resultado.setText(String.valueOf(resultadoResta));
    Calculadora.guardar("resta");
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Error de formato en la resta: Ingresa números válidos.");
}
    }//GEN-LAST:event_restaActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
        try {
        double division = Operaciones.dividir(Double.parseDouble(this.getCampoNum1()), 
                            Double.parseDouble(this.getCampoNum2()));

        Resultado.setText(String.valueOf(division));
        Calculadora.guardar("división");}
        catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Error de formato en la multiplicación: Ingresa números válidos.");
}
    }//GEN-LAST:event_divideActionPerformed

    private void cosenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosenoActionPerformed
        try {
    double anguloCoseno = Double.parseDouble(this.getCampoNum1());
    Resultado.setText(String.valueOf(Operaciones.coseno(anguloCoseno)));
    Calculadora.guardar("coseno");
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Error de formato en el coseno: Ingresa un número válido.");
}
    }//GEN-LAST:event_cosenoActionPerformed

    private void arcosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arcosActionPerformed
        try {
    double numParaArcocoseno = Double.parseDouble(this.getCampoNum1());
    Resultado.setText(String.valueOf(Operaciones.arcocoseno(numParaArcocoseno)));
    Calculadora.guardar("arcocoseno");
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Error de formato en el arcocoseno: Ingresa un número válido.");
}

    }//GEN-LAST:event_arcosActionPerformed

    private void secanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secanteActionPerformed
        try {
    double numParaSecante = Double.parseDouble(this.getCampoNum1());
    Resultado.setText(String.valueOf(Operaciones.secante(numParaSecante)));
    Calculadora.guardar("secante");
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Error de formato en la secante: Ingresa un número válido.");
}
    }//GEN-LAST:event_secanteActionPerformed

    private void cosecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosecActionPerformed
        try {
    double numParaCosecante = Double.parseDouble(this.getCampoNum1());
    Resultado.setText(String.valueOf(Operaciones.cosecante(numParaCosecante)));
    Calculadora.guardar("cosecante");
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Error de formato en el cosecante: Ingresa un número válido.");
}
    }//GEN-LAST:event_cosecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioCal().setVisible(true);
            }
        });
    }

    public String getCampoCodigo() {

        String CampoCodigo = this.campoNum2.getText();
        return CampoCodigo;
    }

    public String getCampoNum1() {
        String CampoNombre = this.campoNum1.getText();
        return CampoNombre;
    }

    public String getCampoNum2() {
        String CampoNombre = this.campoNum2.getText();
        return CampoNombre;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Historial;
    private javax.swing.JLabel Resultado;
    private javax.swing.JButton arcos;
    private javax.swing.JButton arcsen;
    private javax.swing.JButton botonSuma;
    private javax.swing.JTextField campoNum1;
    private javax.swing.JTextField campoNum2;
    private javax.swing.JButton cosec;
    private javax.swing.JButton coseno;
    private javax.swing.JButton divide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton multi;
    private javax.swing.JButton resta;
    private javax.swing.JButton secante;
    private javax.swing.JButton seno;
    // End of variables declaration//GEN-END:variables
}
